version: '3.8'

services:
  bancoDeDados:
    image: mysql:8.0
    container_name: biblioteca_mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: bdBiblioteca
    ports:
      - "3306:3306"
    restart: always